# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4b9168e55471f92a585775764ead5adc13115f053fb659546046fd82a7f9bb8c06aecf20889233d63b47c37bba4ab9514f5a3ed9ebb520b34002fd481b971c08

test:
  secret_key_base: 18f1cbea5c8755839fc0402ecbf7754291bedbd8d57fa08103772765f48d473e49211de3229ce1dbfa16c3256f94b6f6cfe0dbfa9f02a4e79426ad2e7a8494ab

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
